name: Full CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # -------- Setup Java --------
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      # -------- Build Backend --------
      - name: Build Backend
        run: |
          cd backend/jobportal
          mvn clean package -DskipTests

      # -------- Setup Node --------
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # -------- Build Frontend --------
      - name: Build Frontend
        run: |
          cd frontend
          npm install
          npm run build

      # -------- Login to Docker Hub --------
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # -------- Build & Push Backend Image --------
      - name: Build and Push Backend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/jobportal-backend ./backend/jobportal
          docker push ${{ secrets.DOCKER_USERNAME }}/jobportal-backend

      # -------- Build & Push Frontend Image --------
      - name: Build and Push Frontend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/jobportal-frontend ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/jobportal-frontend
